### ISSUE TITLE
Error when try to run

### ISSUE THREAD

**Issue by MayurChandra** [EmreOvunc/Python-SYN-Flood-Attack-Tool#2]
Hi,

Get the following error when try to run

`Packets are sending ...
Traceback (most recent call last):
  File "SYN-Flood.py", line 63, in <module>
    main()
  File "SYN-Flood.py", line 61, in main
    SYN_Flood(dstIP,dstPort,int(counter))
  File "SYN-Flood.py", line 38, in SYN_Flood
    send(IP_Packet/TCP_Packet, verbose=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/sendrecv.py", line 300, in send
    socket = conf.L3socket(*args, **kargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/bpf/supersocket.py", line 58, in __init__
    (self.ins, self.dev_bpf) = get_dev_bpf()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scapy/arch/bpf/core.py", line 98, in get_dev_bpf
    raise Scapy_Exception("No /dev/bpf handle is available !")
scapy.error.Scapy_Exception: No /dev/bpf handle is available !`

**Comment by EmreOvunc** [comment]
Hi,
It seems that you are using an old scapy version.
Please download the latest dev version from here: https://github.com/secdev/scapy/archive/master.zip
then unzip it and install it with python setup.py install
This should fix the bug you're having.
